# Generated by Django 6.0 on 2025-12-03 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ROOM', 'Room'), ('LAB', 'Laboratory'), ('AUDITORIUM', 'Auditorium'), ('MEETING_ROOM', 'Meeting room'), ('LIBRARY', 'Library')], default='ROOM', max_length=20)),
                ('floor', models.IntegerField(default=0, help_text='Piano in cui si trova lo spazio')),
                ('capacity', models.PositiveIntegerField(help_text='Numero massimo di persone ammesse')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='spaces.building')),
                ('equipments', models.ManyToManyField(blank=True, related_name='spaces', to='spaces.equipment')),
            ],
        ),
    ]
