# Generated by Django 5.2.8 on 2025-12-05 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Numero massimo di persone ammesse', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='floor',
            field=models.IntegerField(default=0, help_text='Piano in cui si trova lo spazio', validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
